# -*- mode: ruby -*-
# vi: set ft=ruby :

boxes = {
  'client' => '10',
  'balancer1' => '20',
  'balancer2' => '30',
  'real1' => '40',
  'real2' => '50'
}

Vagrant.configure("2") do |config|
  config.vm.box = "peru/ubuntu-20.04-server-amd64"

  boxes.each do |k, v|
    config.vm.define k do |node|
      node.vm.provision "file", source: "~/.ssh/id_ed25519_vagrant.pub", destination: "/home/vagrant/.ssh/mykey.pub"
      node.vm.network :private_network, :ip => "172.28.128.#{v}"
	node.vm.provision "shell" do |s|
		s.inline = <<-SHELL
			hostnamectl set-hostname $1
			mkdir /root/.ssh
			cat /home/vagrant/.ssh/mykey.pub >> /root/.ssh/authorized_keys
			cat /home/vagrant/.ssh/mykey.pub >> /home/vagrant/.ssh/authorized_keys
			apt-get update
			apt-get -y install nginx curl
		SHELL
		s.args = [k]
	end
    end
  end
end
